name: Generate SHA-256 File

on:
  push:
    paths:
      - 'pve-nag-remover.sh'
  workflow_dispatch:

jobs:
  generate-sha:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true        # ✅ allows push using GITHUB_TOKEN
          fetch-depth: 0                   # ✅ ensures full history for commit/push

      - name: Generate SHA-256 hash file
        run: |
          sha256sum pve-nag-remover.sh > pve-nag-remover.sh.sha256
          cat pve-nag-remover.sh.sha256

      - name: Commit .sha256 file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pve-nag-remover.sh.sha256
          git commit -m "Auto-update SHA-256 for pve-nag-remover.sh" || echo "No changes"
          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}